### ISSUE TITLE
.NET Framework version to high

### ISSUE THREAD

**Issue by royryando** [vbjay/SubscriptionSample#1]
.NET version 4.7 is too high, preferably version 4.5 is sufficient for this application

**Comment by vbjay** [comment]
I develop against current framework, at the time.
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements.
It will run on win 7sp1 and later.

**Comment by vbjay** [comment]
If you wanted to port it to 4.5, 

1. Change the .net framework versions of the projects. 
2. Save and reload.
3. Run update-package -reinstall in package manager console
4. Build projects.
